import { useFrame } from '@react-three/fiber';
import { useMemo, useRef } from 'react';
function MagicParticles(){const points=useRef();const seeds=useMemo(()=>Array.from({length:32},(_,i)=>({x:(Math.random()-.5)*38,z:(Math.random()-.5)*38,y:1+Math.random()*2.5,p:Math.random()*10+i})),[]);useFrame(({clock})=>{if(!points.current)return;const t=clock.getElapsedTime();for(let i=0;i<points.current.children.length;i+=1){const c=points.current.children[i],s=seeds[i];c.position.y=s.y+Math.sin(t*.8+s.p)*.08;}});return <group ref={points}>{seeds.map((s,i)=><mesh key={i} position={[s.x,s.y,s.z]}><sphereGeometry args={[0.06,8,8]}/><meshBasicMaterial color={i%2?'#fff7d1':'#dff6ff'} transparent opacity={0.25}/></mesh>)}</group>}
export default function WorldScene(){
  return <><color attach="background" args={["#d8f2ff"]} /><fog attach="fog" args={['#dff4ff',34,96]} /><ambientLight intensity={0.72} /><hemisphereLight args={['#f2f7ff','#78bf84',0.95]} /><directionalLight position={[14,17,10]} intensity={1.2} color="#ffeacd" />
  <mesh rotation={[-Math.PI/2,0,0]}><circleGeometry args={[76,70]}/><meshStandardMaterial color="#b5e8ab" roughness={0.95}/></mesh>
  <mesh rotation={[-Math.PI/2,0,0]} position={[0,0.01,-1]}><ringGeometry args={[5,16,64]}/><meshStandardMaterial color="#f3e6bd" transparent opacity={0.65}/></mesh>
  {Array.from({length:6}).map((_,i)=><mesh key={i} position={[Math.sin(i*1.7)*28,0.8,Math.cos(i*1.9)*28]}><sphereGeometry args={[6+(i%2)*1.2,14,14]}/><meshStandardMaterial color="#aee0a7"/></mesh>)}
  {Array.from({length:32}).map((_,i)=>{const a=(i/32)*Math.PI*2;const r=22+(i%3)*6;return <group key={`tree-${i}`} position={[Math.cos(a)*r,0,Math.sin(a)*r]}><mesh position={[0,2.2,0]}><cylinderGeometry args={[0.32,0.44,4.2,8]}/><meshStandardMaterial color="#8a5a3b"/></mesh><mesh position={[0,5.1,0]}><sphereGeometry args={[1.9,12,12]}/><meshStandardMaterial color="#7dc88b"/></mesh></group>})}
  {Array.from({length:36}).map((_,i)=><group key={`flowers-${i}`} position={[Math.sin(i*1.9)*(7+(i%6)*2),0,Math.cos(i*2.2)*(6+(i%5)*2)-1]}><mesh position={[0,0.08,0]}><cylinderGeometry args={[0.015,0.02,0.16,5]}/><meshStandardMaterial color="#7cc784"/></mesh><mesh position={[0,0.2,0]}><sphereGeometry args={[0.06,6,6]}/><meshStandardMaterial color={['#ffd6ef','#ffe598','#d8c2ff','#c8f5ff'][i%4]}/></mesh></group>)}
  {Array.from({length:20}).map((_,i)=><group key={`rock-${i}`} position={[Math.sin(i*1.31)*(18+(i%4)*2.5),0.12,Math.cos(i*1.43)*(18+(i%5)*2.4)]}><mesh scale={[1+(i%2)*0.3,.8,1+(i%3)*0.2]}><dodecahedronGeometry args={[0.34,0]}/><meshStandardMaterial color="#a9bbc4" roughness={0.92}/></mesh></group>)}
  {Array.from({length:16}).map((_,i)=><group key={`mush-${i}`} position={[Math.sin(i*1.95)*(13+(i%5)*2.5),0,Math.cos(i*2.11)*(13+(i%4)*2.8)+2]}><mesh position={[0,0.1,0]}><cylinderGeometry args={[0.04,0.05,0.2,8]}/><meshStandardMaterial color="#f3dfc5"/></mesh><mesh position={[0,0.24,0]}><sphereGeometry args={[0.14,10,10]}/><meshStandardMaterial color={i%2?'#ff8cb7':'#b79cff'}/></mesh></group>)}
  <MagicParticles /></>;
}
